# This is an example of a file for filter configuration in CamillaDSP,
# to be used when using LMS with SqueezeLite.
# You will need one file for each sample rate. Change the file name 
# and the samplerate parameter for each samplerate you want to support.

devices:
  samplerate: 44100
  chunksize: 2048
  silence_threshold: -60
  silence_timeout: 3.0
  queuelimit: 1
  capture:
    type: Stdin
    channels: 2
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: sound_out
    format: S32LE

filters:
  clipgain:
    type: Gain
    parameters:
      gain: -5.0
      inverted: false

  peaking_L1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 44.0
      q: 2.438
      gain: -8.1
  peaking_L2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 73.0
      q: 2.021
      gain: -10.4

  peaking_R1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 45.3
      q: 2.004
      gain: -9.4
  peaking_R2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 73.5
      q: 2.749
      gain: -6.3

pipeline:
  - type: Filter
    channel: 0
    names:
      - clipgain
      - peaking_L1
      - peaking_L2

  - type: Filter
    channel: 1
    names:
      - clipgain
      - peaking_R1
      - peaking_R2
