# This is an example file for filter configuration in CamillaDSP.
#
# The samplerate below (44100) is just a value to start with. For
# every change in the samplerate, CamillaDSP will be updated with
# the new samplerate. 

devices:
  samplerate: 44100
  chunksize: 4096
  silence_threshold: -60
  silence_timeout: 3.0
  queuelimit: 1
  capture:
    type: Stdin
    channels: 2
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:1"
    format: S32LE

# Adjust the clip gain if you see information about clipping from
# CamillaDSP in /var/log/syslog.
filters:
  clipgain:
    type: Gain
    parameters:
      gain: -5.0
      inverted: false

# The filter definitions can include IIR filters of different kinds
# and or FIR filters.
#
# IIR filters
# The filters are used for all samplerates.
  peaking_L1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 44.0
      q: 2.438
      gain: -8.1
  peaking_L2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 73.0
      q: 2.021
      gain: -10.4

  peaking_R1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 45.3
      q: 2.004
      gain: -9.4
  peaking_R2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 73.5
      q: 2.749
      gain: -6.3

# FIR filters
# Prepare a convolution file for each samplerate.
# Long story short:
#  - Filters from REW -> rePhase (wine ./rePhase).
#  - Fix the phase response (Paragraphic Phase EQ).
#  - Export the convolution files (in e.g. txt format) for 
#    each samplerate and channel (e.g. R/L).
#
# Wav should work too, but for today that seems to a problem
# with the latest release:
# https://github.com/HEnquist/camilladsp/issues/109
#
# In rePhase I exported with these settings:
#   f     taps
# 44100	  65536
# 48000	  65536
# 88200	 131072
# 96000	 131072
#176400	 262144
#192000	 262144
#352800	 524288
#384000	 524288
# Make sure to have the samplerate in the filename.
# Then, when refering to the files with $samplerate$ in 
# the filename property, the correct file will be
# selected automatically.
  fir_L:
    type: Conv
    parameters:
      type: Raw
      filename: /etc/camilladsp_left_$samplerate$.txt
      format: TEXT

  fir_R:
    type: Conv
    parameters:
      type: Raw
      filename: /etc/camilladsp_right_$samplerate$.txt
      format: TEXT

# Putting it all together.
pipeline:
  - type: Filter
    channel: 0
    names:
      - clipgain
      - peaking_L1
      - peaking_L2
      - fir_L

  - type: Filter
    channel: 1
    names:
      - clipgain
      - peaking_R1
      - peaking_R2
      - fir_R
